### ISSUE TITLE
Adding local genomes: `KeyError: assembly_acc`

### ISSUE THREAD

**Issue by TobyBaril** [xonq/mycotools#4]
Hi! 

I am trying to add some local genomes to my mtdb, following the tutorial/usage instructions. I keep getting the following error with the [example](https://github.com/xonq/mycotools/wiki/Tutorial#add-a-local-genome-to-this-database):

```
# follow commands in tutorial
jgiDwnld -i Ustbr1 -a -g # this works

mtdb p Ustbr1.predb.tsv
##### output #####
Preparing run

Generating omes
Traceback (most recent call last):
  File "/home/toby/miniforge3/envs/mycotools/bin/predb2mtdb", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/toby/miniforge3/envs/mycotools/lib/python3.12/site-packages/mycotools/predb2mtdb.py", line 666, in cli
    omedb, failed = main(predb, refDB, wrk_dir, exit = exit, verbose = True,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toby/miniforge3/envs/mycotools/lib/python3.12/site-packages/mycotools/predb2mtdb.py", line 598, in main
    omedb, failed = gen_omes(infdb, refdb, ome_col = 'ome', forbidden = forbidden,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toby/miniforge3/envs/mycotools/lib/python3.12/site-packages/mycotools/predb2mtdb.py", line 306, in gen_omes
    refdb_accs = set([x for x in list(refdb['assembly_acc']) if x])
                                      ~~~~~^^^^^^^^^^^^^^^^
KeyError: 'assembly_acc'
```

I then tried with a small test sheet that is automatically generated by predb2mtdb and get the same error:

Here is the small test I am using:
```
#assembly_acc	previous_ome	genus	species	strain	version	assemblyPath	gffPath	genomeSource (ncbi/jgi/new)	useRestriction (yes/no)
GCA_927399515_3	laesul3	Laetiporus	sulphureus	NA	3	/data/toby/fungi_htt/1_sourcing_genomes/dtolGenomes/include/GCA_927399515.3_gfLaeSulp1.3_genomic.fna	/data/toby/fungi_htt/1_sourcing_genomes/dtolGenomes/include/GCA_927399515.3_gfLaeSulp1.3_genomic.gff3	new	no
```

Then output of `mtdb p test_2.tsv` :
```
Preparing run

Generating omes
Traceback (most recent call last):
  File "/home/toby/miniforge3/envs/mycotools/bin/predb2mtdb", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/toby/miniforge3/envs/mycotools/lib/python3.12/site-packages/mycotools/predb2mtdb.py", line 666, in cli
    omedb, failed = main(predb, refDB, wrk_dir, exit = exit, verbose = True,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toby/miniforge3/envs/mycotools/lib/python3.12/site-packages/mycotools/predb2mtdb.py", line 598, in main
    omedb, failed = gen_omes(infdb, refdb, ome_col = 'ome', forbidden = forbidden,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toby/miniforge3/envs/mycotools/lib/python3.12/site-packages/mycotools/predb2mtdb.py", line 306, in gen_omes
    refdb_accs = set([x for x in list(refdb['assembly_acc']) if x])
                                      ~~~~~^^^^^^^^^^^^^^^^
KeyError: 'assembly_acc'
```

Is there something locally that could be causing this issue? 

Thanks in advance for your help!

Toby

**Comment by TobyBaril** [comment]
This might be unrelated, but essentially I'm trying to add some genomes from the Darwin Tree of Life project to my database. Currently the assemblies are on NCBI but lacking annotations. I've done a quick + dirty annotation for the moment with augustus (as I don't need them for the moment, but I know they are required for MTDB), but the GFF3 curation is failing for all these genomes when I run:
```
mtdb update -i [primary_db] --predb predb.tsv
```

But here I don't get the key error, I just get `GFF3 curation failed for [genome_name]`. The augustus outputs are quite different from those in the existing db. I've tried to look in the documentation to see what fields are actually required but seem to have lost this now, do you have any advice on how to get these GFFs to play nicely? They currently look like this after I've messed with them a bit:

```
##gff-version 3
# This output was generated with AUGUSTUS (version 3.5.0).
# AUGUSTUS is a gene prediction tool written by M. Stanke (mario.stanke@uni-greifswald.de),
# O. Keller, S. König, L. Gerischer, L. Romoth, Katharina Hoff, Henry Mehlan and Daniel Honsel.
# Please cite: Mario Stanke, Mark Diekhans, Robert Baertsch, David Haussler (2008),
# Using native and syntenically mapped cDNA alignments to improve de novo gene finding
# Bioinformatics 24: 637-644, doi 10.1093/bioinformatics/btn013
# No extrinsic information on sequences given.
# Sources of extrinsic information: M RM 
# Initializing the parameters using config directory /home/toby/miniforge3/envs/mycotools/config/ ...
# neurospora_crassa version. Using default transition matrix.
# Looks like /data/toby/fungi_htt/1_sourcing_genomes/dtolGenomes/include/GCA_927399515.3_gfLaeSulp1.3_genomic.fna is in fasta format.
# We have hints for 0 sequences and for 0 of the sequences in the input set.
#
# ----- prediction on sequence number 1 (length = 4563458, name = OV656674.1) -----
#
# Predicted genes for sequence number 1 on both strands
# start gene g1
OV656674.1      AUGUSTUS        gene    1070    4795    0.68    +       .       ID=gene_g1
OV656674.1      AUGUSTUS        start_codon     1070    1072    .       +       0       Parent=gene_g1
OV656674.1      AUGUSTUS        CDS     1070    4792    0.68    +       0       ID=cds_g1.t1.cds;Parent=gene_g1
OV656674.1      AUGUSTUS        stop_codon      4793    4795    .       +       0       Parent=gene_g1
# protein sequence = [MRDSLLASLSRAGSPVPGRVAAATTLPIEASAVPPLANAPGPSGSAVAAATAIGADVSRYVTQRSREAVQAASSWVEL
# VALWPGSYREGVKPLMKEIWELAGSYAGATEAFERLSVHQKSPTTARTYPQHYAAVRIPAMQTSSEFGRTNDALSFKRELEDTVRNAKEAMLDVEYRA
# RSNEVHYLQTRLDPQKWVRDLHAVIERIYARDVQPFALEPPSLGGALGDGDVVMGDGGAQPPPPARDSWTVTKGARDERTFARNLAMHLIPRMMVVRR
# GAVANHREKQHAKESLKRAADTSAGASVPANLKQVVKAQVQAALASTSKGSVSIASVSLDIFLNPFTQTSSAKPKAPVAKPSGGGPTRSSGSKRPSGA
# AKRAKKNSKPYSTAGSGATADMRVVRRVFNLVGAQEDRSEDRAGRKREGEGQSESLADLLVKVLVSPWEYDRPSTYPDEILDLPSSVAQAVVWSRAPL
# ELIESARFRAGVHMGPNVSVPLELLVHASVGLNYLFASPPRASMVVRAWREFERRVRWSAVFVKESKTPYDPDYDSGRRSQKEPPLAPRAIEDGLLAG
# RQLLRSRVRHAHTARIVSRNVLLSSLVDVTPLLEVLKDNAYLIVPTDKNLGVAVVAAEWYVAECRKLLTNDVKIRSIDAYVAEILRSDLADKLEAVLL
# RHQSWLEDGNPQLWDYLRSTLIVRSGDGSAYLPEFKGLPKIHKTPWRMRPIVPGHSLIMSPSAKFVSKSLKPIIAQRPYVLESSRKLARDLSELRLLG
```

Thanks again!

**Comment by TobyBaril** [comment]
I might be getting closer to solving this - sorry for all the separate messages! So I have managed to run: 

```
mtdb update --init /data/toby/fungi_htt/1_sourcing_genomes/dtolGenomes/ --predb ../predb.tsv
```

And I have a successful `mtdb` file, along with the directories with `faa`, `fna`, and `gff3`, each with 31 non-empty files in them, as expected.

Now when I try to add this to my main db:

```
### reattach to the main database
mtdb -i /data/toby/fungi_htt/1_sourcing_genomes/mycotools_db/mycotoolsdb/
##### output
# Establishing fungi connection
# /data/toby/fungi_htt/1_sourcing_genomes/mycotools_db/mycotoolsdb/mtdb/20240717.mtdb

### add the new genomes
mtdb update -a /data/toby/fungi_htt/1_sourcing_genomes/dtolGenomes/mycotoolsdb/mtdb/20241010.mtdb

ERROR: some paths in addition MTDB do not exist: 
        FNA: True; GFF3: True; FAA: True
```

I get the same error if I attach the new database and try to add the original one, which makes me think there is a potential issue with the resolution of filepaths when adding genomes from a new db in a different directory. I've checked the `data` dir of the new db with the genomes to add, and all files look as expected.

**Comment by xonq** [comment]
Hey Toby,

In response to your first message, I could not reproduce your error and I think I understand why through your next messages. 

1) `mtdb predb2mtdb` is for adding genomes to an existing and initialized MTDB. you should have already initialized an MTDB. You can check if you are linked to an initialized MTDB by running `mtdb` on its own. You can initialize a new database from a `predb` using the command you attempted in 2.

2) `mtdb update -i [primary_db] --predb predb.tsv` - this command indicates to me you are not initialized. The `-i` flag means initialize, and what you are putting for `[primary_db]` should be the new initialization directory if you are initializing from a `predb.tsv`. 

3) I have not accounted for Augustus GFF3s in curation. The one you're presenting me looks different from standard GFF3s. I would atttempt to use an Augustus GTF if you have it, some GTFs can be accounted for.

4) I think to summarize what you were doing incorrectly is that you were unlinked trying to add a predb to an existing database. You then attempted to initialize a new database with the predb, linked to the database you actually wanted, and tried to add the source MTDB you initialized to the one you actually wanted, but the database you were adding lacked paths because you were trying to add the source MTDB. You fixed your issue by linking to the correct database and just running predb2mtdb from there. Some of this is obfuscated and needs to be made easier.

**Comment by TobyBaril** [comment]
Awesome thanks for the explanation! I think I confused myself and ended up linking + unlinking and all sorts! It all worked super well in the end - thanks for making such a great tool!
