### ISSUE TITLE
Resume is stuck

### ISSUE THREAD

**Issue by jorgecnavarrom** [xonq/mycotools#6]
Hi
I've run into some problems when running mtdb. It took a long time to download all the JGI data (~a week), and after that, it started to generate proteomes. At this step, it froze for about a day, and because I had had some updates to the OS (Ubuntu), I decided to stop and reboot (so perhaps this already caused some problem). It resumed ok until it reaches a point where nothing seems to happen (though it's still running 100% on one cpu). I've tried to restart it at this step a few times, but I cancel after about a day without seeing any change (e.g. files written, or new terminal activity). My question is if this is normal and I should wait more, or is there something wrong with my initial run that caused this behavior (would like to avoid starting from scratch as much as possible).

Current output:
```
mtdb update -c 8 --resume 20241009 --nonpublished -i . 

Dependency check:
datasets:      /home/jorge/miniconda3/envs/mycotools/bin/datasets

Update MycotoolsDB

Execution began: 2024-10-26 19:20:34.928603
PRIMARY MTDB:                 /media/jorge/Elements/FUNGAL_GENOMES/MycoDB_2024-10-09/mycotoolsdb/mtdb/20241009.mtdb
UPDATE:                       False
INITIALIZE:                   .
ADD:                          None
INCLUDE RESTRICTED:           True
RESUME:                       20241009
RETRY FAILED:                 False
RETRY FORBIDDEN:              False
SAVE RAW DATA:                False

NCBI email: **
NCBI api key (blank if none): 
JGI email: **
JGI password (required): 

Establishing fungi connection

Initializing run
        Acquiring NCBI metadata
Collecting 16,874 genome records [------------------------------------------------]   0% 0/16874
Collecting 16,874 genome records [===========>------------------------------------]  28% 4653/16874
Downloading: ncbi_dataset.zip    2.73MB valid zip archive
Validating package files [================================================] 100% 5/5
                4653 genomes queried from GenBank
                1 genome(s) queried from RefSeq

Assimilating MycoCosm (1 download/minute)
        Searching NCBI for MycoCosm overlap
        Downloading MycoCosm data
                Redundancy check
                        2612 genomes to assimilate
                Logging into JGI
                Retrieving `xml` directories
                Downloading JGI data
                        All downloaded, rerun off
        Curating MycoCosm data
 75%|███████████████████████████████████████████████████████████████████████████████████████████▋                              | 1944/2587 [00:03<00:01, 394.83it/s]conthr1|Conth1 failed GFF3 curation
                pospla2|Pospl1 failed GFF3 curation
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2587/2587 [00:05<00:00, 494.02it/s]
                klumar2|Kluma1 failed GFF3 curation
                micbol1|Micbo1 failed GFF3 curation
                volvol1|Volvo1 failed GFF3 curation
                pseela1|Pseel1 failed GFF3 parsing
                venpir1|Venpi1 failed FNA parsing
                basund1|Basun1 failed FNA parsing
                botdot1|Botdo1_1 failed FNA parsing
                rhyruf1|Rhyru1_1 failed FNA parsing
                hyspul1|Hyspu1_1 failed FNA parsing
                orpsp.1|Orpsp1_1 failed FNA parsing
                venina1|Venin1 failed FNA parsing
                mucrac1|Mucrac1 failed FNA parsing
                mucend1|Mucend1 failed FNA parsing
                muclan1|Muclan1 failed FNA parsing
                parpol1|Parpo1 failed FNA parsing
                mucfus1|Mucfus1 failed FNA parsing
                dibbae1|Dibbae1 failed FNA parsing
                enthep1|Enthe1 failed GFF3 curation
                copscl1|Copscl1 failed GFF3 curation
                phisco1|Phisc1 failed GFF3 curation
                consp.2|ConPMI546 failed GFF3 curation
                aurvul1|Aurvu1 failed GFF3 curation
                hymrad1|Hymrad1 failed GFF3 curation
                gymand1|Gyman1 failed GFF3 curation
```

The content of the `log` folder (where I see some activity):
![Screenshot_20241027_103806](https://github.com/user-attachments/assets/d233d441-517d-46bf-ab85-5910bd5fe277)

I installed mycotools using conda, and updated the package to 0.32.4 two days ago.

As an extra remark subfolders inside of `data` are empty

**Comment by xonq** [comment]
Hi Jorge, 

Unfortunately, JGI stringently limits their API's download rate, so the download rate cannot be increased. The `data` subfolders won't be populated until the end of the update.

Proteome generation is a multiprocessing step, so this could be some multiprocessing error(s) that clogged the pool and isn't being reported. Alternatively, I haven't run into an error here, though I do recall it being slow on large runs, which could be explained by the pool closing.

Anyway, I released an update that bypasses the pool when using a single CPU. I would either 1) continue running, or 2) retry the run with `--cpu 1` and see if there is an error output. Let me know if either of these work.

**Comment by jorgecnavarrom** [comment]
thanks for the quick reply @xonq ! I'll give it a try and let you know

**Comment by jorgecnavarrom** [comment]
Hi. Short update: I tried with the new version and 1 cpu. It seemed stuck for about two days without anything being printed on screen but now it's making progress again! (processing NCBI data).

**Comment by xonq** [comment]
Hey again @jorgecnavarrom - glad to hear it is proceeding. Was it faster with 1 CPU? I am suspicious there is some hangup in the multiprocessing pool joining.

As a side note, this long delay doesn't happen in subsequent updates in my experience.

**Comment by jorgecnavarrom** [comment]
Hi again. It finished during the night! 

I didn't perceive this as being faster... but then again I never let it continue after about a day. 

Thanks again!
